### ISSUE TITLE
Question about order in `Bdd`.

### ISSUE THREAD

**Issue by lengyijun** [sybila/biodivine-lib-bdd#18]
```
if flip_out_if == Some(decision_var) {
    // If we are flipping output, we have to compute subtasks in the right order.
    if new_high.is_none() {
        stack.push(comp_high);
    }
    if new_low.is_none() {
        stack.push(comp_low);
    }
} else {
    if new_low.is_none() {
        stack.push(comp_low);
    }
    if new_high.is_none() {
        stack.push(comp_high);
    }
}
```

You seem to keep the order in `Bdd.0`. But I think except the first two and the last one(root), other `BddNode`'s order doesn't matter.

## Motivates
I'm trying to rewrite `project` function to improve performance. But my approach will mess up `BddNode`'s  order.
I want to know if the order is useful in some certain cases?

**Comment by daemontus** [comment]
You are right, except for "root" and terminals, the order is largely irrelevant.

There is one place where it matters though: At the moment, `Bdd` uses `#[derive(Eq, PartialEq)]` to test for equivalence, which relies on the fact that when the order of nodes is the same, two equivalent BDDs are also equivalent on a byte level. 

If you break the order of the nodes, test for equivalence must be added either as a separate algorithm, or using some appropriate wrapper around `apply` with the if-and-only-if operator. However, I believe this is a reasonable tradeoff for a faster projection algorithm. We were actually thinking about lifting this restriction for similar reasons, but we never had a use-case where the projection (or other possible order-breaking operation) was the bottleneck, so it is a "nice to have todo" at the moment.

**Comment by lengyijun** [comment]
```
// test equivalence of bdd1 and bdd2
assert!(bdd1.iff(&bdd2).is_true());
assert_eq!(bdd1.0.len(),bdd2.0.len());
```
Is this enough to prove bdd1 is as simple as bdd2?

**Comment by daemontus** [comment]
Yes, `bdd1.iff(&bdd2).is_true()` should be a correct equivalence check regardless of node order.

**Comment by daemontus** [comment]
There is now a new, faster `project` algorithm which I believe resolves the point of the original question. 

The order of BDD nodes will probably be relaxed in version `1.0.0` (i.e. next time a breaking change is possible). But there currently isn't a firm roadmap towards `1.0.0`.
