### ISSUE TITLE
Support `Conditional` ternary operator

### ISSUE THREAD

**Issue by zao111222333** [sybila/biodivine-lib-bdd#52]
Thanks for this crate!
I want to know do you plan to support `BooleanExpression::Condition(cond,then_exp,else_exp)`. The conditional operator `cond ? then_exp : else_exp` is equal to `(cond & then_exp) | (!cond & else_exp)`.
If it is in the plan, I can help for the parser implementation.

**Comment by daemontus** [comment]
Hi! We don't have a specific roadmap for this feature yet. But if you are willing to implement it, I'll be happy to merge it! :)

**Comment by zao111222333** [comment]
Great! I will try to implement this feature!

**Comment by daemontus** [comment]
Awesome, thank you!
